version: '3'

volumes:
  mysqldata:

services:
  web:
    build: .
    env_file: ./.env
    ports:
      - '3000:3000'
    volumes:
      - '.:/my-blog'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - 'mysqldata:/var/lib/mysql'
      - './mysql/log:/var/log/mysql/error.log'